/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'productIds' : Array<bigint>,
  'userId' : bigint,
  'name' : string,
  'orderTime' : Time,
  'totalAmount' : number,
  'profile' : UserProfile,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'image' : string,
  'price' : number,
}
export interface ProductUpdate {
  'name' : string,
  'description' : string,
  'image' : string,
  'price' : number,
}
export type QuoteStatus = { 'in_progress' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'received' : null };
export interface ServiceQuote {
  'id' : bigint,
  'status' : QuoteStatus,
  'serviceType' : string,
  'name' : string,
  'createdTime' : Time,
  'email' : string,
  'message' : string,
  'address' : Address,
  'phone' : string,
  'adminNotes' : string,
}
export interface ServiceQuoteCreate {
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'address' : Address,
  'phone' : string,
}
export interface ServiceQuoteUpdate {
  'status' : QuoteStatus,
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'address' : Address,
  'phone' : string,
  'adminNotes' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : Address,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'archiveProduct' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<[Product], undefined>,
  'getActiveProductCount' : ActorMethod<[], bigint>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getQuote' : ActorMethod<[bigint], ServiceQuote>,
  'getQuotes' : ActorMethod<[], Array<ServiceQuote>>,
  'getTotalProductCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [UserProfile, Array<bigint>, Address, number],
    Order
  >,
  'requestServiceQuote' : ActorMethod<[ServiceQuoteCreate], bigint>,
  'restoreProduct' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductUpdate], undefined>,
  'updateQuote' : ActorMethod<[bigint, ServiceQuoteUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];