/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
  'price' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : Address,
  'phone' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'productIds' : IDL.Vec(IDL.Nat),
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'orderTime' : Time,
  'totalAmount' : IDL.Float64,
  'profile' : UserProfile,
});
export const QuoteStatus = IDL.Variant({
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'received' : IDL.Null,
});
export const ServiceQuote = IDL.Record({
  'id' : IDL.Nat,
  'status' : QuoteStatus,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'createdTime' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'address' : Address,
  'phone' : IDL.Text,
  'adminNotes' : IDL.Text,
});
export const ServiceQuoteCreate = IDL.Record({
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'address' : Address,
  'phone' : IDL.Text,
});
export const ProductUpdate = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
  'price' : IDL.Float64,
});
export const ServiceQuoteUpdate = IDL.Record({
  'status' : QuoteStatus,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'address' : Address,
  'phone' : IDL.Text,
  'adminNotes' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminByEmail' : IDL.Func([IDL.Text], [], []),
  'archiveProduct' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'getActiveProductCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getQuote' : IDL.Func([IDL.Nat], [ServiceQuote], ['query']),
  'getQuotes' : IDL.Func([], [IDL.Vec(ServiceQuote)], ['query']),
  'getTotalProductCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [UserProfile, IDL.Vec(IDL.Nat), Address, IDL.Float64],
      [Order],
      [],
    ),
  'requestServiceQuote' : IDL.Func([ServiceQuoteCreate], [IDL.Nat], []),
  'restoreProduct' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductUpdate], [], []),
  'updateQuote' : IDL.Func([IDL.Nat, ServiceQuoteUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
    'price' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : Address,
    'phone' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : Address,
    'productIds' : IDL.Vec(IDL.Nat),
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'orderTime' : Time,
    'totalAmount' : IDL.Float64,
    'profile' : UserProfile,
  });
  const QuoteStatus = IDL.Variant({
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'received' : IDL.Null,
  });
  const ServiceQuote = IDL.Record({
    'id' : IDL.Nat,
    'status' : QuoteStatus,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'createdTime' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'address' : Address,
    'phone' : IDL.Text,
    'adminNotes' : IDL.Text,
  });
  const ServiceQuoteCreate = IDL.Record({
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'address' : Address,
    'phone' : IDL.Text,
  });
  const ProductUpdate = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ServiceQuoteUpdate = IDL.Record({
    'status' : QuoteStatus,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'address' : Address,
    'phone' : IDL.Text,
    'adminNotes' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminByEmail' : IDL.Func([IDL.Text], [], []),
    'archiveProduct' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'getActiveProductCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getQuote' : IDL.Func([IDL.Nat], [ServiceQuote], ['query']),
    'getQuotes' : IDL.Func([], [IDL.Vec(ServiceQuote)], ['query']),
    'getTotalProductCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [UserProfile, IDL.Vec(IDL.Nat), Address, IDL.Float64],
        [Order],
        [],
      ),
    'requestServiceQuote' : IDL.Func([ServiceQuoteCreate], [IDL.Nat], []),
    'restoreProduct' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductUpdate], [], []),
    'updateQuote' : IDL.Func([IDL.Nat, ServiceQuoteUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };